### ISSUE TITLE
效果不好

### ISSUE THREAD

**Issue by whxhy666** [pantDevesh/Content-aware-Seam-Carving#1]
你好，使用 您的源代码，在实现图像放大的时候，效果很不好，没有你那样的效果，是什么原因呢？

**Comment by pantDevesh** [comment]
I have tested it on the given images and it works fine on them. Also, if you increase width and height at the same time it might not work as expected. If you want to get an enlarged image as shown here then pass "300 216" as input.
Input-
enter 1 for resize or 2 for object removal
1
current image size 300 196
enter new image size
300 216
